### ISSUE TITLE
Enhancement: make a release

### ISSUE THREAD

**Issue by tpoindessous** [mbachry/collectd-systemd#9]
Hi !

Thanks for your work.

Could you please make a release ( and make a new release when you will update your code ) ? 

With a release, we could get your code with a HTTPS link instead of a git clone and it will be easier to follow your code between two releases.

Currently, we have forked your repo and we maintains our release tags.

Thanks !

**Comment by mbachry** [comment]
That's a great point, thanks. I made an initial release here: https://github.com/mbachry/collectd-systemd/releases/tag/v1.0.0

**Comment by tpoindessous** [comment]
Hi ! 

Thanks !
